# ...
class Config(object):
    configuration = {
        # ...
        "processing": {
            # ...
            "bytes": {
                "enabled": Boolean(True),
            },
        },
    }
# ...
